### ISSUE TITLE
Add a reading list

### ISSUE THREAD

**Issue by theotherphil** [rust-lang/chalk#161]
There are a few references to papers scattered through Niko’s blog posts. It would be helpful to have a single list containing those papers and whatever other books or papers Chalk contributors are drawing inspiration from.

Edit: ah, it looks like the comments in chalk-engine/src/lib.rs provide at least a partial list.

**Comment by memoryruins** [comment]
Various links for anyone else coming across this issue:

The Rustc Guide contains a [Trait solving (new-style)](https://rust-lang-nursery.github.io/rustc-guide/traits/index.html) section, which includes a [bibliography](https://rust-lang-nursery.github.io/rustc-guide/traits/bibliography.html) listing some background material. 

From the bibliography, [A proof procedure for the logic of Hereditary Harrop formulas](https://dl.acm.org/citation.cfm?id=868380), by Gopalan Nadathur, was mentioned in a few of the blog posts. [Programming with Higher-order Logic](https://www.amazon.com/Programming-Higher-Order-Logic-Dale-Miller/dp/052187940X), by Dale Miller and Gopalan Nadathur, has lived up to the description, "it's the kind of book where you learn something new every time you open it."

The resources listed in ``chalk-engine/src/lib.rs`` appear to share with the list in the rustc guide and chalk-engine's readme section [heritage and acroynms](https://github.com/rust-lang-nursery/chalk/blob/master/chalk-engine/src/README.md#heritage-and-acroynms). At the root of the repo is a short and to the point [glossary](https://github.com/rust-lang-nursery/chalk/blob/master/GLOSSARY.md), which lists some reading materials near the bottom. I suggest building local docs of the repo with ``cargo doc``, especially since  #175 has made it easier to grok its structure and its forthcoming use in rustc.

**Comment by Mcat12** [comment]
The bibliography has moved to the chalk book, here is the new link: https://rust-lang.github.io/chalk/book/bibliography.html
