### ISSUE TITLE
Infinite stack growth in chalk

### ISSUE THREAD

**Issue by matklad** [rust-lang/chalk#280]
This issue is to track a problem, discussed in this [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/infinite.20stack.20growth.20in.20chalk).

The original problem was observed in rust-analyzer (rust-analyzer/rust-analyzer#2052): chalk exhausts all available memory by expanding the stack: https://gist.github.com/matklad/c6320c19b08afc8e6d8ca8612354d5b8

Here's a stand-alone rust-analyzer test that shows the problem:

https://github.com/matklad/rust-analyzer/commit/d907b00f440ca0a127e6975994a54391ce5a976d

There's no isolated chalk test at the moment for this.

**Comment by nikomatsakis** [comment]
Relevant factors:

* rust-analyzer size must be 4 (the default used in chalk, 10, makes the problem go away)

**Comment by nikomatsakis** [comment]
OK, so I've reproduced the problem, and I know what it is, but I'm not sure yet what I think is the best solution.

You can find the test case on my branch [issue-280-rust-analyzer-infinite-growth][b]. 

[b]: https://github.com/nikomatsakis/chalk-ndm/tree/issue-280-rust-analyzer-infinite-growth

The problem is this:

* To impose the maximum size requirement of 4, we introduce inference variables
* The answer to these inference variables winds up being unnormalized projection types (I'm not quite sure how that comes about yet, actually, have to look a bit more into that)
* When we go to incorporate the answer, we wind up with new subgoals that never ends

Ah wait -- I think the problem is actually the opposite. The variable comes from the *answer*, and the unnormalized projection type appears in the environment (it's the type that was replaced with a variable).

**Comment by flodiebold** [comment]
After #279, am I right in assuming this manifests as OOM instead of stack overflow now?

**Comment by matklad** [comment]
@flodiebold to be precise, this never was a stackoverflow, because chalk used to grow the stack automatically.

**Comment by jackh726** [comment]
Ok, so I've looked into this a bit tonight and figured I would write down more or less what I've found, in case other people want to take a look (or have ideas on the best solution).

@nikomatsakis's comment above (https://github.com/rust-lang/chalk/issues/280#issuecomment-552621555) is correct, but I'll go into more detail.

### Reproducing the issue ###
I used Niko's repro from above, but also had to set the `max_size` for the solver to `4` [here](https://github.com/rust-lang/chalk/blob/3ef20308e7882a3e5fb71a6f28caab8cc71cf5f0/chalk-solve/src/solve.rs#L77). Since this issue was first discovered, `chalk-engine` doesn't recurse when pursuing a strand, but instead iterates ([here](https://github.com/rust-lang/chalk/blob/3ef20308e7882a3e5fb71a6f28caab8cc71cf5f0/chalk-engine/src/logic.rs#L415)). And, this is exactly where the issue occurs. For debugging, I find it's easy enough to limit the loop iterations to 5 for this test and is enough to reveal the problem and see that with `CHALK_DEBUG=2`.

### Details ###
Be forewarned, in this section, I'm just going to essentially go through the details of what is happening in the loop that result in the infinite loop. I won't go into how we ended up here or why. It'll also be mostly debug output, but can be useful to think about what's happening.

Upon first entering `pursue_strand` here, we are pursuing a strand on the table with the goal
```
: | table goal = UCanonical {
: :     canonical: Canonical {
: :         value: InEnvironment {
: :             environment: Env([ProjectionEq(<!1_0 as ParallelIterator>::Item = !1_2), FromEnv(!1_1: FnOnce<Tuple<<!1_2 as Try>::Ok, <!1_2 as Try>::Ok>>), FromEnv(!1_2: Try), FromEnv(!1_0: ParallelIterator)]),
: :             goal: Implemented(!1_0: ParallelIterator),
: :         },
: :         binders: [],
: :     },
: :     universes: 2,
: : }
```
This is the "root" goal.

The strand has 3 subgoals, the one that matters here is
```
Positive(
	InEnvironment {
		environment: Env([ProjectionEq(<!1_0 as ParallelIterator>::Item = !1_2), FromEnv(!1_1: FnOnce<Tuple<<!1_2 as Try>::Ok, <!1_2 as Try>::Ok>>), FromEnv(!1_2: Try), FromEnv(!1_0: ParallelIterator)]),
		goal: Â¯\_(ãƒ„)_/Â¯,
	},
),
```
This goal when followed first gets truncated to
```
InEnvironment { environment: Env([ProjectionEq(<!1_0 as ParallelIterator>::Item = !1_2), FromEnv(!1_1: FnOnce<Tuple<<!1_2 as Try>::Ok, ?0>>), FromEnv(!1_2: Try), FromEnv(!1_0: ParallelIterator)]), goal: Â¯\_(ãƒ„)_/Â¯ }
```
(The second `<!1_2 as Try>::Ok>` in the `Tuple` is converted to the inference variable `?0`)

This leads to an answer
```
Answer { subst: Canonical { value: ConstrainedSubst { subst: [?0 := ^0], constraints: [] }, binders: [Ty(U1)] }, ambiguous: true }
```

When this answer is applied to the original goal, this unification happens
```
: : : | unify(a=?1,
: : : :       b=<!1_2 as Try>::Ok) {
: : : : | unify_ty_ty(a=?1,
: : : : :             b=<!1_2 as Try>::Ok) {
: : : : | }
: : : | }
```
which removes the original subgoal, but now adds a new one
```
Positive(
	InEnvironment {
		environment: Env([ProjectionEq(<!1_0 as ParallelIterator>::Item = !1_2), FromEnv(!1_1: FnOnce<Tuple<<!1_2 as Try>::Ok, <!1_2 as Try>::Ok>>), FromEnv(!1_2: Try), FromEnv(!1_0: ParallelIterator)]),
		goal: ProjectionEq(<!1_2 as Try>::Ok = ?1),
	},
),
```

This subgoal gets truncated to 
```
InEnvironment { environment: Env([ProjectionEq(<!1_0 as ParallelIterator>::Item = !1_2), FromEnv(!1_1: FnOnce<Tuple<<!1_2 as Try>::Ok, ?2>>), FromEnv(!1_2: Try), FromEnv(!1_0: ParallelIterator)]), goal: ProjectionEq(<!1_2 as Try>::Ok = ?1) }
```
which eventually leads to the answer
```
Answer { subst: Canonical { value: ConstrainedSubst { subst: [?0 := ^0, ?1 := (Try::Ok)<!1_2>], constraints: [] }, binders: [Ty(U1)] }, ambiguous: false }
```

And when applied with this unification
```
: : : | unify(a=?3,
: : : :       b=<!1_2 as Try>::Ok) {
: : : : | unify_ty_ty(a=?3,
: : : : :             b=<!1_2 as Try>::Ok) {
: : : : | }
```
results in a new (replacing the last) subgoal
```
Positive(
	InEnvironment {
		environment: Env([ProjectionEq(<!1_0 as ParallelIterator>::Item = !1_2), FromEnv(!1_1: FnOnce<Tuple<<!1_2 as Try>::Ok, <!1_2 as Try>::Ok>>), FromEnv(!1_2: Try), FromEnv(!1_0: ParallelIterator)]),
		goal: ProjectionEq(<!1_2 as Try>::Ok = ?3),
	},
),
```
which looks exactly like the last one, except with `?3` instead of `?1`. Which results in a subgoal table and a similar answer application. And each of the answers applications succeed, so the loop continues.

### Possible solutions/thoughts ###
- It would be easy enough to "get out" of this loop by returning `QuantumExceeded` even on answers. Maybe only on answers with substitutions (otherwise just continue the loop). However, I don't think would get us anywhere in the longer run since the logic will always get "stuck" here regardless.
- We could also compare the previous subgoal with the new conditions that we get. If they are the same, we Flounder. Not sure about this.
- When a goal is truncated to search for a subgoal table, should the `environment` also be truncated? I think if it wasn't, then that would solve the problem, but I'm not sure if there are other reasons for that.
- There might be other solutions, but that's all I have for now.


Hopefully this writeup is useful for *someone* (even if it's me later).
