### ISSUE TITLE
extract rustc-guide content to make a chalk book

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#286]
I think we should extract the rustc-guide content on "new style" trait solving and instead have it live in the chalk repository, effectively trying to build a chalk book. 

I'd actually like to hear @spastorino and @mark-i-m's take on this -- I'm now leaning towards having salsa, polonius, and chalk (and maybe other very self-contained projects) host their own books, with links from the rustc-guide to those books. This is both to make it easier to keep those books in sync with the state of the project and to help the projects be more "standalone".

**Comment by spastorino** [comment]
I think that's a good idea and I like the idea of rustc-guide having links to them.

One question I have though is ... I guess the books would explain the libraries outside of the context of the compiler?, in that case, would rustc-guide have an "integration" chapter that explain how those libraries are used in the compiler and how are integrated? and the links to the libraries would be from those chapters? or the idea is just that the book on the library repo would already contain integrations with the compiler.
Anyway, in one case or another I think is a good idea :).

**Comment by mark-i-m** [comment]
Hmm... I'm skeptical.

I might be biased since I personally don't favor the compiler being broken into different repos.

But I think my main concern is that we fragment knowledge around different repos and books. I don't like that precedent. The guide would no longer be a one stop shop -- it would effectively become what the forge was: a collection of links to random places. It would also make it much harder to get a full picture of the whole compiler, since you would have to go read a bunch of different books.

I'm also wondering if you have a plan to have draconian CI with link checking blocking all new PRs. If not, then I'm very skeptical that a separate book would actually be kept up to date.

**Comment by tmandry** [comment]
I think putting the content in the same repo makes it a _lot_ easier to keep things in sync. I also like the idea of having an "integration chapter" inside rustc-guide which points to the chalk guide.

It would be kind of nice if we similarly put the rustc-guide inside the rust repo, but I don't really see that happening.

**Comment by jackh726** [comment]
Small thing, but I'm gonna add to this that `CHALK_DEBUG` should be documented somewhere.

**Comment by jackh726** [comment]
Also, somewhere in the book should be a reading list (https://github.com/rust-lang/chalk/issues/161)

**Comment by jackh726** [comment]
We have a book :) With a reading list and [documentation](https://rust-lang.github.io/chalk/book/contribution_guide.html#running-and-debugging) of `CHALK_DEBUG`. Closing :)
