### ISSUE TITLE
deferred: can we / should we truncate the environment, and how to avoid loops?

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#306]
In https://github.com/rust-lang/chalk/pull/294, we opted to stop truncating the environment. The problem was due to an infinite loop that arose in some rust-analyzer cases. The scenario [was described on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/144729-wg-traits/topic/design.20meeting.202019.2E12.2E09/near/182989871) recently but is also covered in #280 and #289.

In short, we would truncate a projection `Foo::Bar` from the environment and replace it with an inference variable `?X`. When we get back an answer, we would unify `Foo::Bar` with the value inferred for `?X` -- which would up being a fresh inference variable. This would create a projection goal, but that projection goal includes the same environment that we started with, and hence that same environment would get truncated again. This would result in the cycle beginning anew.

For now, we opted to just stop truncating the environment, because it isn't really needed at the moment -- Rust doesn't generate queries that grow the environment in indefinite ways. But we may want to revisit this with another fix, or -- depending on how we resolve normalization -- this may become a non-issue in the future. 

This issue has been assigned to @zaharidichev via [this comment](https://github.com/rust-lang/chalk/issues/306#issuecomment-612038103).

**Comment by jackh726** [comment]
I think now that truncation in general now just leads to `Floundering`, we should also just check if the `Environment` is too large. I think this question is still *valid* if we ever add truncation back in, but I'm not sure it should be an open issue, rather than just a note when `Environment` truncation is checked.

This should be pretty easy to fix, so I'll mark it as a `good first issue`.
