### ISSUE TITLE
Long-running analysis on large project with time spent in 'ensure_root_answer'

### ISSUE THREAD

**Issue by t-mw** [rust-lang/chalk#314]
I'm testing `rust-analyzer` in Emacs with a large-ish project (~18000 loc excluding dependencies), and running into long pauses spent in chalk. This is a stack trace from a profiler attached to `ra_lsp_server`, showing where most of the time is spent (in ms) from triggering a `highlight` request to the language server:

<img width="854" src="https://user-images.githubusercontent.com/9677694/71523041-18504600-28bf-11ea-881b-cb92d47a1b85.png">

I'm not sure what the problem is based on the output, but happy to run other tests and/or provide private access to the repo.

I'm running on OSX and have also enabled the `useClientWatching` option for `rust-analyzer`.

/cc @matklad

**Comment by jackh726** [comment]
So, having all the time spent in `ensure_root_answer` makes complete sense, because that's where the solving is done. However, what's surprising to me is how much time is spent in `get_or_create_table_for_ucanonical_goal`, which seems mostly to be caused by `program_clauses_for_goal`.

@nikomatsakis is this about what you would expect?

**Comment by t-mw** [comment]
I tried setting `CHALK_DEBUG=1` for a 'goto definition' request that took around 40 seconds. The log is attached, I truncated it but it's still quite large.

[chalk.log.zip](https://github.com/rust-lang/chalk/files/4010611/chalk.log.zip)

**Comment by nikomatsakis** [comment]
My take from that stack trace is that the problem seems to be relating to creating the program clauses -- it looks like it's enumerating out associated types? If I had to guess, I would guess that there are a large number, and we are really wastefully walking over and over them.

In general, the existing code in chalk-solve is very inefficient. It doesn't do any sort of caching and just redoes all the work each time. We probably need to improve that. But it'd be really great if we could reproduce the perf problems a bit more. I haven't looked at the chalk.log.zip file, that might help to confirm the hypothesis.

**Comment by nikomatsakis** [comment]
@t-mw I presume the source code is not public? :) Any clues as to what it is?

**Comment by t-mw** [comment]
I've invited you and @jackh726 to the project (https://github.com/t-mw/chalk-314-repro-rs/). There are instructions for reproducing the issue in the readme. I haven't added associated types to any traits defined in the project, but there are obviously a few dependencies that use them.

**Comment by jackh726** [comment]
Just tested the repro case using the current week's version of rust-analyzer and this looks fixed for me!

@t-mw if you still run into issues, feel free to file another
