### ISSUE TITLE
Better guidance for projections

### ISSUE THREAD

**Issue by flodiebold** [rust-lang/chalk#429]
I think the following test, or something similar, should pass:
```rust
#[test]
fn projection_guidance() {
    test! {
        program {
            trait Iterator { type Item; }
            #[non_enumerable]
            trait Step {}

            struct Range<T> {}

            impl<T> Iterator for Range<T> where T: Step {
                type Item = T;
            }
        }

        goal {
            exists<T> {
                exists<U> {
                    <Range<T> as Iterator>::Item = U
                }
            }
        } yields[SolverChoice::recursive()] {
            "Ambiguous; definite substitution { [?0 := ?0.0, ?1 = ?0.0] }"
        }
    }
}
```
I.e. the recursive solver should be able to tell that there is only one impl that could possibly apply, so we know the `Item` type. This is derived from the following real-world case (from rust-analyzer/rust-analyzer#4072:
```rust
enum Option<T> {}
trait Iterator {
    type Item;

    fn next(&mut self) -> Option<Self::Item>;
}

trait Step { }
impl Step for i32 {}
impl Step for u32 {}

struct Range<T>(T, T);

impl<A: Step> Iterator for Range<A> {
    type Item = A;
}

fn main() {
    let x = Range(0, 10).next();
}
```
which rustc manages to [figure out](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=16e099b6ca27a76998ab1eac3f0ab280). (This isn't related to integer type variables / fallback, it's just an easy way to get a type variable.)

The SLG solver gives `Ambiguous; definite substitution for<?U0> { [?0 := ^0.0, ?1 := (Iterator::Item)<Range<^0.0>>] }`, which is also not very helpful, but that's related to [other problems](https://github.com/rust-lang/chalk/issues/234), I think.

I haven't really looked into why this doesn't work in the recursive solver or how to fix it; I think it may be that the solver just gives up too early when one subgoal flounders (in this case the `?0: Step` goal). It could be a good first issue for getting into the recursive solver. It may be more complicated though.

This issue has been assigned to @Mcat12 via [this comment](https://github.com/rust-lang/chalk/issues/429#issuecomment-630303770).

**Comment by Mcat12** [comment]
I've started looking into this and I think I've found why the solver fails, though I may need some guidance on how to properly fix it.

@rustbot claim

The gist is that the recursive solver gets to to the point where it has to prove `Implemented(^0.0: Step)`, but it does not receive any clauses which it can use. I think it just `Implemented(^0.0: Step) :- FromEnv(^0.0: Step)` and `FromEnv(^0.0: Step)`, but they are not made available.

<details>
<summary>
Snippet from debug output
</summary>
<p>

```
| solve_goal(UCanonical { canonical: Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(^0.0: Step) }, binders: [U0 with kind type] }, universes: 1 }) {
: | solve_new_subgoal(canonical_goal=UCanonical { canonical: Canonical { value: InEnvironment { environment: Env([]), goal: Implemented(^0.0: Step) }, binders: [U0 with kind type] }, universes: 1 }, depth=StackDepth { depth: 3 }, dfn=DepthFirstNumber { index: 3 }) {
: : | prog_clauses {
: : : | program_clauses_for_goal(goal=Implemented(^0.0: Step), environment=Env([])) {
: : : : | program_clauses_that_could_match(goal=Implemented(^0.0: Step)) {
: : : : | }
: : : | }
: : | }
: : | prog_solution=Ok(Ambig(Unknown))
: : | solve_new_subgoal: loop iteration result = Ok(Ambig(Unknown)) with minimums Minimums { positive: DepthFirstNumber { index: 18446744073709551615 } }
: | }
```

</p>
</details>

I've modified [`program_clauses_that_could_match`] to generate the trait datum clauses before doing the non-enumerable check (adding the implemented -: from_env rule). I was originally going to try and avoid the `Err(Floundered)` by checking the environment for `FromEnv(^0.0: Step)`, but the environment is completely empty. I'm also not sure if this is the right approach, since I don't really have any background in the recursive solver. Let me know if there's a more "idiomatic" way to solve this, and in the meantime I'll keep plugging away at it.

[`program_clauses_that_could_match`]: https://github.com/rust-lang/chalk/blob/b64e5a80f8beafd8b2e83c8083497beafef5cd5d/chalk-solve/src/clauses.rs#L173-L175

**Comment by flodiebold** [comment]
Returning `Ambig(Unknown)` for `Implemented(^0.0: Step)` is correct, I think. When the solver gets a goal like `Implemented(^0.0: Step)`, it cannot enumerate all types that implement `Step`, so even if it did have some other program clauses for this goal, and those program clauses did give solutions, it still doesn't know whether there are other solutions. I think the actual problem is in the layer above that, where it's trying to apply the `Normalize` rule and getting `Ambig` for the subgoal.

**Comment by Mcat12** [comment]
I was a little confused by why `Normalize` required `Implemented` rules, as the types should still be equivalent regardless of if they are implemented or well-formed. Perhaps the `Implemented` rules should be moved to another clause?

**Comment by Mcat12** [comment]
Reading the debug output, a solution is found but the ambiguous solution from `Implemented(^0.0: Step)` is used instead because it has a higher priority:
```
preferring solution: Ambig(Unknown) over Unique(Canonical { value: ConstrainedSubst { subst: [?0 := ^0.0, ?1 := (Iterator::Item)<Range<^0.0>>], constraints: [] }, binders: [U0 with kind type] }) because of higher prio
```

There is a similar test in #433 (no associated types though) while seems to work as expected:
https://github.com/rust-lang/chalk/blob/c8135bbd7c0e56d83e729d4fc33df811513c1f92/tests/test/impls.rs#L643-L660
However, the PR is mainly for the SLG solver.

**Comment by flodiebold** [comment]
> I was a little confused by why Normalize required Implemented rules, as the types should still be equivalent regardless of if the trait is implemented or well-formed. Perhaps the Implemented rules should be moved to another clause?

This is why: #235 
The `Normalize` rule needs to check the where clauses of the impl.

> Reading the debug output, a solution is found but the ambiguous solution from Implemented(^0.0: Step) is used instead because it has a higher priority

That's also correct, the low-priority solution isn't really helpful here either, it's just a placeholder for the associated type in case we find no other solution.

> However, the PR is mainly for the SLG solver.

The PR also contains a fix for the recursive solver, it's just much smaller apparently :wink:

**Comment by Mcat12** [comment]
So I took another look at the [Type equality and unification] logic to figure out what path the logic is expected to take in order to arrive at the `Ambiguous; definite substitution { [?0 := ?0.0, ?1 = ?0.0] }` solution. Once we reach the goal `Normalize(<Range<T> as Iterator>::Item -> T)` we produce the following clause:
```
forall<T> {
    Normalize(<Range<T> as Iterator>::Item -> T) :-
        Implemented(T: Step)
}
```
The documentation proposes an additional condition, `Implemented(Range<T>: Iterator)`, but it seems fine for the implementation to elude it since it is always true given `Implemented(T: Step)`.

Intuitively, we know `T` implements `Step` because it is a condition of the impl. That is, there should be a `FromEnv(T: Step)` in the environment once we enter the impl. I think this is where the problem occurs, because the implementation does not do this and then trips up because `Step` is non-enumerable. @flodiebold this is where I'd like tap your knowledge, because I'm not sure where/when the recursive solver is expected to add facts to the environment. Is it just a bug that it doesn't happen once we enter the impl, or is that expected? Looking through the places where the environment is given facts/clauses, maybe we should be pushing a `GoalData::Implies` to our `Fulfill` instance when entering the impl?

[Type equality and unification]: https://rust-lang.github.io/chalk/book/clauses/type_equality.html#associated-type-projection-and-normalization

**Comment by flodiebold** [comment]
> The documentation proposes an additional condition, Implemented(Range<T>: Iterator), but it seems fine for the implementation to elude it since it is always true given Implemented(T: Step).

That's the documentation being outdated; the condition for the `Normalize` rule used to be just that the corresponding trait is implemented, but that was wrong because of #235. And yeah, the current conditions imply that condition (but not the other direction).

> Intuitively, we know T implements Step because it is a condition of the impl. That is, there should be a FromEnv(T: Step) in the environment once we enter the impl.

I'm not sure what exactly you see as "entering the impl" here. We try to apply the `Normalize` rule, and that requires us to prove `Implemented(?0: Step)`, we can't just assume it. We would be able to assume it if we were trying to prove an implication like `T: Step => Normalize(<Range<T> as Iterator>::Item -> T)`, but that's not the situation we're in here.

**Comment by Mcat12** [comment]
I mean "entering the impl" as the for loop over all the impls of `Iterator` (maybe it should be further down the logical chain, like when we try to prove `Implemented(T: Step)`?):
https://github.com/rust-lang/chalk/blob/01690cff453d471a8184bc0f3de8fdf32301cd77/chalk-solve/src/clauses.rs#L328-L341

We are given that `T: Step` in the impl parameters, therefore we should know `FromEnv(T: Step)` while we are checking if the normalization is valid (I'm not directly assuming `Implemented(T: Step)`). If this isn't true, then how else would we show `[?0 := ?0.0, ?1 = ?0.0]`?

**Comment by flodiebold** [comment]
> we should know FromEnv(T: Step) while we are checking if the normalization is valid 

We don't know that; otherwise the result would be that the normalization is always valid, which it isn't.

But yes, the reasoning here is basically "if this were true, then the substitution would be `[?0 := ?0.0, ?1 = ?0.0]`. So I guess it could be possible to detect the situation, solve the goal assuming the condition, and then see what the substitution would be. I just think this is probably too complicated of a solution, and there should be a simpler fix for this; because we already have the substitution when we're trying to prove the `Normalize` rule, we just need to return it when we get an ambiguous result. There may be additional conditions necessary though.

**Comment by Mcat12** [comment]
Ok, now I feel a little silly, but at least I understand the solver code a little better. #443 fixes this issue for the recursive solver (a simple 6-line change). However, it regresses the SLG solver to return `Ambiguous; no inference guidance` instead of `Ambiguous; definite substitution { [?0 := ?0.0, ?1 = ?0.0] }"`.

**Comment by flodiebold** [comment]
Actually, I think that's the correct way to write what I meant :slightly_smiling_face: 

> However, it regresses the SLG solver to return Ambiguous; no inference guidance instead of Ambiguous; definite substitution for<?U0> { [?0 := ^0.0, ?1 := (Iterator::Item)<Range<^0.0>>] }.

Hm, well, the previous answer from the SLG solver is wrong anyway, and the SLG solver has problems with projections anyway (#234), so this doesn't seem that worrying to me, but I also don't know enough about the SLG solver to know whether there's a problem in the PR.
