### ISSUE TITLE
add flags to `InternedTy` and `InternedRegion` types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/chalk#627]
In rustc, we have a "flags" system that propagates information about a type upward and which can be used to shortcircuit a lot of work. The [`TypeFlags`] propagates various bits. Each time a type is interned, the flags from any subtypes are combined to form the flags for the new interned type. This allows us to do things like skip subtrees that don't contain the sort of thing we are looking for efficiently.

In the meeting today we discussed different ways of doing this. I'll add a comment with more notes.

**Comment by jackh726** [comment]
What do we need flags for on lifetimes? In rustc, there are only flags on types, I thought?

Definition in rustc: https://github.com/rust-lang/rust/blob/a9cd294cf2775441e713c7ee2918b728733b99f5/compiler/rustc_middle/src/ty/mod.rs#L501

Going to mark this as a good first issue, since this should be fairly straightforward.

**Comment by matthewjasper** [comment]
I don't think that a flags field makes much sense on lifetimes, because they're fairly fast to compute directly (just a match).
There are also flags on `Predicate` in rustc.

**Comment by chfont** [comment]
I've started working on this.

@rustbot claim
