### ISSUE TITLE
tracing-tree gets activated by chalk-recursive

### ISSUE THREAD

**Issue by matklad** [rust-lang/chalk#686]
`chalk-ir` crate has an optional dep on `tracing-tree`, but this dep is in the default feature. `chalk-recursive` depends on `chalk-ir` *without* `default-features = false`, and so it unconditionally pulls tracing tree.

Either `tracing-full` should not be a default feature, or chalk crates should use `default-features=false` for path dependencies.

**Comment by detrumi** [comment]
I'm assuming you meant `chalk-solve`, because that's the crate with the optional dependency on `tracing-tree`.

Using `default-features=false` inside chalk crates would mean that they wouldn't have tracing enabled, so I don't think that's an option. Likewise, making it non-default would have the same result.

We should propagate the feature to all crates that depend on `chalk-solve` instead, so in this case just `chalk-recursive` (`chalk-engine` and `chalk-integration` shouldn't really be used from outside). Then consumers of `chalk-recursive` can can opt out of tracing support.

**Comment by matklad** [comment]
A related issue is that chalk doesn't set `default-featuers = false` on tracing-subscriber. It probably should?
